version: 2
jobs:
    one:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - echo 1
    two:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - echo 2

workflows:
    version: 2
    build:
        jobs:
            - one
            - two
