version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Download Cytoscape
          command: apt-get update && apt-get install openjdk-8-jdk curl xvfb -y && curl -O https://github.com/cytoscape/cytoscape/releases/download/3.7.2/cytoscape-3.7.2.tar.gz && tar xf cytoscape-3.7.2.tar.gz && rm cytoscape-3.7.2.tar.gz
      - run:
          name: Start Cytoscape
          command: xvfb-run bash ./cytoscape-unix-3.7.2/cytoscape.sh
          background: true
      - run:
          name: Check CyREST
          command: sleep 300 && pgrep -a cytoscape
          
